import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
export default function Blog() {
    // 🔹 الداتا كلها في نفس الصفحة
    const blogData = [
        {
            id: 1,
            title: "كيف يُسهّل النظام الإلكتروني التواصل بين المدرسة وأولياء الأمور؟",
            date: "2026-02-04",
            author: "warda samy",
            excerpt: "التواصل الفعال بين المدرسة وأولياء الأمور هو عنصر حيوي لنجاح العملية التعليمية...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 2,
            title: "دليل شامل لفهم ميزات Pioneers E-School: من إدارة الجداول إلى تتبع الأداء",
            date: "2026-02-02",
            author: "warda samy",
            excerpt: "في عالم يتزايد فيه تعقيد العمليات الإدارية والتعليمية، أصبحت الحاجة إلى أنظمة إدارة متكاملة...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 3,
            title: "التخلص من الفوضى الورقية: كيف يُحوّل Pioneers E-School عمليات التسجيل إلى رقمية؟",
            date: "2026-01-30",
            author: "warda samy",
            excerpt: "التحول الرقمي في المدارس يقلل الأخطاء ويوفر الوقت والجهد على الإدارة...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 4,
            title: "كيف تعزز بوابات الطلاب مشاركة الطلاب في العملية التعليمية؟",
            date: "2026-01-28",
            author: "warda samy",
            excerpt: "بوابات الطلاب الرقمية أصبحت عنصرًا أساسيًا لزيادة التفاعل والانضباط...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 5,
            title: "كيف يغير الذكاء الاصطناعي مستقبل أنظمة إدارة المدارس؟",
            date: "2026-01-25",
            author: "warda samy",
            excerpt: "الذكاء الاصطناعي يساعد المدارس على تحليل الأداء واتخاذ قرارات ذكية...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 6,
            title: "أهمية أنظمة إدارة المدارس في تحسين الأداء الإداري",
            date: "2026-01-22",
            author: "warda samy",
            excerpt: "الإدارة الذكية تقلل الأعباء الورقية وتزيد من كفاءة العمل داخل المدرسة...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 7,
            title: "كيف تساهم الأنظمة السحابية في تطوير التعليم الحديث؟",
            date: "2026-01-20",
            author: "warda samy",
            excerpt: "الحلول السحابية توفر مرونة عالية وسهولة وصول للبيانات في أي وقت...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 8,
            title: "التخلص من Excel: لماذا تحتاج المدارس لنظام إدارة متكامل؟",
            date: "2026-01-18",
            author: "warda samy",
            excerpt: "الاعتماد على الإكسيل يسبب أخطاء متكررة مقارنة بالأنظمة الحديثة...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 9,
            title: "أهمية أمان البيانات في أنظمة إدارة المدارس",
            date: "2026-01-16",
            author: "warda samy",
            excerpt: "حماية بيانات الطلاب والمعلمين أصبحت ضرورة لا غنى عنها...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 10,
            title: "كيف يساعد نظام إدارة المدارس في تحسين التحصيل الدراسي؟",
            date: "2026-01-14",
            author: "warda samy",
            excerpt: "تحليل النتائج والتقارير الذكية يدعم تحسين مستوى الطلاب...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 11,
            title: "إدارة الرسوم المدرسية بشكل ذكي وآمن",
            date: "2026-01-12",
            author: "warda samy",
            excerpt: "الأنظمة الرقمية تسهّل التحصيل وتقلل الأخطاء المالية...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 12,
            title: "كيف تساهم التقارير الذكية في اتخاذ القرار الإداري؟",
            date: "2026-01-10",
            author: "warda samy",
            excerpt: "التقارير الفورية تساعد الإدارة على رؤية شاملة ودقيقة...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 13,
            title: "أهمية بوابة ولي الأمر في أنظمة إدارة المدارس",
            date: "2026-01-08",
            author: "warda samy",
            excerpt: "بوابة ولي الأمر تعزز الشفافية والثقة بين المدرسة والأسرة...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 14,
            title: "كيف تدعم الأنظمة الإلكترونية المعلمين داخل الفصل؟",
            date: "2026-01-06",
            author: "warda samy",
            excerpt: "الأدوات الرقمية تساعد المعلم على التركيز على التعليم لا الإدارة...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 15,
            title: "التحول الرقمي ودوره في تطوير المدارس الخاصة",
            date: "2026-01-04",
            author: "warda samy",
            excerpt: "المدارس الرقمية أكثر قدرة على المنافسة وتحقيق الجودة...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 16,
            title: "كيف تنظم أنظمة الإدارة المدرسية الجداول الدراسية؟",
            date: "2026-01-02",
            author: "warda samy",
            excerpt: "جدولة الحصص إلكترونيًا توفر وقتًا كبيرًا وتقلل التعارض...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 17,
            title: "أهمية نظام الكنترول الإلكتروني في المدارس",
            date: "2025-12-30",
            author: "warda samy",
            excerpt: "الكنترول الإلكتروني يقلل الأخطاء ويرفع دقة النتائج...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 18,
            title: "إدارة شؤون الطلاب بطريقة ذكية",
            date: "2025-12-28",
            author: "warda samy",
            excerpt: "تنظيم بيانات الطلاب يسهل المتابعة ويزيد الكفاءة...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
        {
            id: 19,
            title: "كيف تحسن الأنظمة الرقمية تجربة الطالب؟",
            date: "2025-12-26",
            author: "warda samy",
            excerpt: "الطالب يصبح أكثر تفاعلًا عند استخدام أدوات تعليمية حديثة...",
            img: "src/assets/schoolimg/نور_الايمان_العالميه.webp",
        },
        {
            id: 20,
            title: "مستقبل التعليم مع أنظمة إدارة المدارس الذكية",
            date: "2025-12-24",
            author: "warda samy",
            excerpt: "المدارس الذكية هي مستقبل التعليم الحديث...",
            img: "src/assets/schoolimg/Al-Awael_Private_Schools.webp",
        },
    ];
    return (_jsxs("div", { className: "px-4 py-8 md:px-12 md:py-14 bg-gray-50", dir: "rtl", children: [_jsx("h1", { className: "text-3xl md:text-4xl font-bold mb-10 text-center text-[#9E7C2F]", children: "\u0627\u0644\u0645\u062F\u0648\u0646\u0629" }), _jsxs("div", { className: "flex justify-center gap-6 bg-white\r\n       p-4 rounded-x shadow-sm mb-10", children: [_jsx(Button, { className: "px-6 bg-cyan-800 text-white hover:bg-cyan-900 \r\n         w-[200px]", children: "\u0634\u0631\u0648\u062D\u0646\u0627" }), _jsx(Button, { variant: "outline", className: "px-6 border-cyan-800 text-cyan-800\r\n          w-[200px] hover:bg-cyan-800 hover:text-white", children: "\u0645\u0642\u0627\u0644\u0627\u062A\u0646\u0627" })] }), _jsx("div", { className: "grid gap-8 sm:grid-cols-2 lg:grid-cols-3", children: blogData.map((item) => (_jsxs("div", { className: "group bg-white rounded-2xl shadow-sm\r\n             hover:shadow-xl transition-all duration-300 overflow-hidden \r\n             flex flex-col", children: [_jsx("div", { className: "h-48 overflow-hidden", children: _jsx("img", { src: item.img, alt: item.title, className: "w-full h-full object-cover\r\n                 group-hover:scale-105 transition duration-300" }) }), _jsxs("div", { className: "p-5 flex flex-col flex-1", children: [_jsx("h2", { className: "text-lg font-bold mb-2 text-gray-800 line-clamp-2", children: item.title }), _jsxs("div", { className: "text-xs text-gray-500 mb-3", children: [item.date, " \u2014 ", item.author] }), _jsx("p", { className: "text-gray-600 text-sm line-clamp-3 flex-1", children: item.excerpt }), _jsx("button", { className: "mt-5 self-start text-[#9E7C2F] font-semibold text-sm hover:underline", children: "\u0627\u0642\u0631\u0623 \u0627\u0644\u0645\u0632\u064A\u062F \u2192" })] })] }, item.id))) })] }));
}
